// eslint-disable-next-line camelcase
import { Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";

const PlusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PlusJakartaSans.className + "bg-blue-950 dark" }>{children}</body>
    </html>
  );
}
